## ASSIGNMENT

##  Group_1
### Dave
### Dennis
### Martha
### Nana Kwabena
### Fatima 

Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10. Expected Output: [[ 2 3 4] [ 5 6 7] [ 8 9 10]]

Write a NumPy program to create a null vector of size 10 and update the sixth value to 11. [ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] Update sixth value to 11 [ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

Write a NumPy program to create an array with values ranging from 12 to 38. Expected Output: [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

Write a NumPy program to reverse an array (the first element becomes the last). Original array: [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37] Reverse array: [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

Write a NumPy program to convert an array to a floating type. Sample output: Original array [1, 2, 3, 4] Array converted to a float type: [ 1. 2. 3. 4.]

Write a NumPy program to create a 2D array with 1 on the border and 0 inside. Expected Output: Original array: [[ 1. 1. 1. 1. 1.] ................... [ 1. 1. 1. 1. 1.]]

Write a NumPy program to find the number of elements in an array. It also finds the length of one array element in bytes and the total bytes consumed by the elements. Expected Output: Size of the array: 3 Length of one array element in bytes: 8 Total bytes consumed by the elements of the array: 24

In [4]:
# Q1 creating 3*3 matrix
import numpy as np
Matx = np.arange(2,11)
Matx

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
Matx.reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [11]:
# Q2
a1 = np.zeros(11)
a1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
a1[5] = 11
a1

array([ 0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.,  0.])

In [ ]:
# Q3

In [13]:
values = np.arange(12,38)
values

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

In [ ]:
# Q4

In [15]:
reverse = np.sort(values)[::-1]
reverse

array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])

In [19]:
# Q5
values = np.array([1,2,3,4])
values

array([1, 2, 3, 4])

In [22]:
print(values.astype(float))

[1. 2. 3. 4.]


In [23]:
# Q6

# Define dimensions of the array
rows = 5
cols = 5

# Create an array of zeros
array = np.zeros((rows, cols))

# Fill borders with ones
array[0] = 1
array[-1] = 1
array[:, 0] = 1
array[:, -1] = 1

print("Original array:")
print(array)


Original array:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [24]:
# Create the NumPy array
arr = np.array([1, 2, 3], dtype=np.int64)

# Find the size of the array (number of elements)
size_of_array = arr.size

# Find the length of one array element in bytes
element_size_in_bytes = arr.itemsize

# Find the total bytes consumed by the elements of the array
total_bytes_consumed = size_of_array * element_size_in_bytes

# Print the results
print("Size of the array:", size_of_array)
print("Length of one array element in bytes:", element_size_in_bytes)
print("Total bytes consumed by the elements of the array:", total_bytes_consumed)


Size of the array: 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24
